-- Add up migration script here
-- Generated by the database client.
CREATE TABLE node."account"(
                               id SERIAL NOT NULL,
                               created_at timestamp without time zone,
                               user_name varchar(125),
                               address varchar(128),
                               updated_at timestamp without time zone,
                               PRIMARY KEY(id)
);