sqlx database setup
CREATE USER prome WITH PASSWORD 'prome_123456';
 
 -- 授予新用户数据库连接和创建权限
 GRANT CONNECT ON DATABASE prome TO prome;
 GRANT CREATE ON DATABASE prome TO prome;
 
 -- 授予新用户模式权限
 GRANT USAGE ON SCHEMA node TO prome;
 GRANT USAGE ON SCHEMA public TO prome;
 GRANT CREATE ON SCHEMA node TO prome;
 GRANT CREATE ON SCHEMA public TO prome;
 
 -- 授予新用户表和序列权限
 GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA node TO prome;
 GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO prome;
 GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA node TO prome;
 GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO prome;
 
 -- 确保将这些权限应用于将来创建的表和序列
 ALTER DEFAULT PRIVILEGES IN SCHEMA node GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prome;
 ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prome;
 ALTER DEFAULT PRIVILEGES IN SCHEMA node GRANT USAGE, SELECT ON SEQUENCES TO prome;
 ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO prome;
 
 -- 设置 search_path
 ALTER USER prome SET search_path TO node, public;

